/* eslint-disable no-undef */
/**
 * Argos PR shape rules via danger.js.
 *
 * Runs per-PR in .github/workflows/danger.yml. Supplements commitlint
 * (which enforces message shape) and CodeRabbit (which reviews code
 * quality) with PR-level structural rules:
 *
 *   1. Size cap — warn on PRs the reviewer can't reasonably load. Hard-fail
 *      at 2000 reviewable LOC. THREE carve-outs:
 *        (a) Pure-deletion (additions === 0 && deletions > 0): skipped —
 *            no per-line review value when removing code; reviewers
 *            spot-check the file list, not the bytes.
 *        (b) Format-only commits (`style(<scope>): prettier|format ...`):
 *            subtracted from the LOC total via computeFormatOnlyLOC().
 *        (c) Label exemption: PR has 'size-cap-exempt' label AND author
 *            association is MEMBER / OWNER / COLLABORATOR. Drive-by
 *            contributors cannot self-exempt.
 *   2. Cross-subsystem sprawl — warn when a single PR spans more than
 *      three top-level src/ areas.
 *   3. Tests-required — fail when server code changes without a
 *      matching test delta.
 *   4. Migration-drift — warn when migrations and schema.sql drift
 *      out of sync.
 *   5. Lockfile sync — fail when package.json is modified but
 *      package-lock.json is not; warn on the reverse. Catches the
 *      "forgot to commit the lockfile" class of bug. Source pattern:
 *      https://danger.systems/js/tutorials/dependencies.
 *   6. Native-addon dependency guard — fail if better-sqlite3 or
 *      node-pty (Argos's native modules) move into devDependencies.
 *      @sveltejs/adapter-node only externalizes `dependencies`; native
 *      addons in devDeps get bundled and break at server startup with
 *      `ReferenceError: __filename is not defined`. Per AGENTS.md.
 *   7. New-dependency visibility — when ANY dependency is added or
 *      removed in this PR, post a `message()` listing the entries.
 *      Aligns with Argos's "no npm install without approval" rule.
 *   8. PR description quality — warn when PR body is empty or under
 *      100 chars. The PR description is the first thing reviewers
 *      see on GitHub; commit messages alone don't surface in the
 *      summary view.
 *
 * Industry-norm references: the canonical Danger.js example at
 * https://danger.systems/js/index uses 600 LOC warn() with no hard
 * block. Argos retains the 2000-LOC hard block as discipline for
 * ordinary feature PRs while adding carve-outs (a, b, c) for legitimate
 * exceptions — structurally consistent with how popular OSS Danger
 * configurations handle large-but-low-review-value PRs.
 *
 * `fail` rules block the merge; `warn` rules post a comment but do not
 * block. `message` rules are informational only.
 */

// Include deleted files too — a PR that deletes server code is still a
// server-code change and must satisfy the tests-required gate. Dedupe so a
// file that appears in multiple danger.git arrays isn't counted twice.
const changed = Array.from(
	new Set([
		...(danger.git.modified_files || []),
		...(danger.git.created_files || []),
		...(danger.git.deleted_files || [])
	])
);

// ── 1. PR size cap (human-authored lines only — exclude generated files) ─
// Hard cap raised from 1200 → 2000 on 2026-04-29 to support phase-level
// PR bundling per memory `feedback_bulk_pr_bundling.md`. Spec-026 sub-phases
// total ~1700-2000 LOC when bundled (wrapper + spec docs + consumer
// migrations + roadmap flip). 2000 is the new ceiling; soft warn at 500
// stays as the splitting nudge for non-phase-bundled PRs.
const PR_SIZE_SOFT = 500;
const PR_SIZE_HARD = 2000;
// Globs for files that bloat the raw diff without being reviewable prose.
// Lock files, changelogs, and snapshot fixtures all fall in here — they can
// legitimately add thousands of lines on a small PR and would defeat the gate.
const GENERATED_GLOBS = [
	'package-lock.json',
	'**/package-lock.json',
	'yarn.lock',
	'pnpm-lock.yaml',
	'**/pnpm-lock.yaml',
	'CHANGELOG.md',
	'**/CHANGELOG.md',
	// Fallow baseline files are machine-generated by `fallow {dead-code,health,dupes}
	// --save-baseline`. They snapshot the day-1 finding state and refresh on
	// re-baseline; reviewers shouldn't count their JSON line counts against
	// the human-authored LOC cap.
	//
	// PR #108 (session-3 fallow batch) hit the 2000-LOC cap reporting 8899
	// human-authored lines — the baseline regenerations contributed ~6500 of
	// those because some glob libraries default to dotfiles=false. Enumerate
	// the three baseline filenames explicitly so the exclusion fires
	// regardless of glob-library dotfile policy. The wildcards stay as a
	// catch-all for any future fallow-* baseline file.
	'.fallow-deadcode-baseline.json',
	'.fallow-dupes-baseline.json',
	'.fallow-health-baseline.json',
	'.fallow-*-baseline.json',
	'**/.fallow-*-baseline.json',
	// Vendored upstream code under static/webtak/{novnc,vendor}/ is
	// byte-for-byte from novnc/noVNC + nodeca/pako. Reviewers don't audit it
	// line-by-line — it's a snapshot of an external project. Treat as
	// generated for size-cap purposes; the manifest test
	// (tests/integration/vnc-vendor-manifest.test.ts) is what reviewers
	// actually look at.
	'static/webtak/novnc/**',
	'static/webtak/vendor/**'
];
/**
 * Human-authored LOC = total LOC minus everything matched by GENERATED_GLOBS.
 * Used by both the size-cap gate and the micro-PR carve-out.
 */
async function computeHumanAuthoredLOC() {
	const total = await danger.git.linesOfCode();
	let generated = 0;
	for (const pat of GENERATED_GLOBS) {
		generated += await danger.git.linesOfCode(pat);
	}
	return { lineCount: Math.max(0, total - generated), generated };
}

// Format-only commits are deterministic prettier / formatter output. No
// review value is added by capping their LOC — re-running the same tool on
// the pre-commit state reproduces the diff exactly. Detected by Conventional
// Commits subject pattern: `style(<scope>): prettier ...` or
// `style(<scope>): format ...`. Authors opt in by using these subjects for
// pure formatter sweeps. Mixed PRs (format commit + non-format commit) get
// per-commit subtraction: the format commit's LOC contribution is excluded
// while non-format commits' LOC still counts toward the cap.
//
// Discovered 2026-05-06: PR #115 was a 6031-LOC bundle of which ~5800 was a
// single `npm run format` sweep on Phase 9 spec docs + .svelte files.
// Splitting an auto-format diff into per-file PRs adds zero review signal
// at >100× CI cost. Codifying the carve-out in `dangerfile.js` is the
// professional alternative to admin-bypassing the gate (see
// `feedback_no_admin_bypass_daily_loc_cap.md`).
const FORMAT_COMMIT_RE = /^style\([^)]+\):\s+(prettier|format)\b/;
const { execSync } = require('node:child_process');

function computeFormatOnlyLOC() {
	const commits = (danger.git && danger.git.commits) || [];
	let total = 0;
	const matched = [];
	for (const c of commits) {
		const subject = ((c && c.message) || '').split('\n')[0];
		if (!FORMAT_COMMIT_RE.test(subject)) continue;
		try {
			const out = execSync(`git show --shortstat --format="" ${c.sha}`, {
				encoding: 'utf8'
			});
			const ins = Number((out.match(/(\d+) insertion/) || ['', 0])[1]);
			const del = Number((out.match(/(\d+) deletion/) || ['', 0])[1]);
			total += ins + del;
			matched.push({ sha: c.sha.slice(0, 7), subject, loc: ins + del });
		} catch {
			// Conservative: a commit whose stat we can't read counts toward cap.
		}
	}
	return { total, matched };
}

/**
 * Pure-deletion carve-out (a). Returns the exemption message if the PR is
 * pure deletion (additions === 0 && deletions > 0), or null if not exempt.
 */
function checkPureDeletionExemption() {
	const pr = danger.github?.pr;
	if (!pr) return null;
	const additions = pr.additions ?? 0;
	const deletions = pr.deletions ?? 0;
	if (additions !== 0 || deletions <= 0) return null;
	const changedFiles = pr.changed_files ?? 0;
	return `Pure-deletion PR (${deletions} lines removed across ${changedFiles} files). Size cap skipped — reviewers should spot-check the file list, not read line-by-line.`;
}

/**
 * Label-based exemption carve-out (c). Returns the exemption message if the
 * PR carries the 'size-cap-exempt' label AND author is a trusted association
 * (MEMBER / OWNER / COLLABORATOR), or null if not exempt.
 */
function checkLabelExemption(reviewable) {
	const pr = danger.github?.pr;
	if (!pr) return null;
	const labels = (danger.github?.issue?.labels ?? []).map((l) => l.name);
	if (!labels.includes('size-cap-exempt')) return null;
	const authorAssoc = pr.author_association ?? 'NONE';
	if (!['MEMBER', 'OWNER', 'COLLABORATOR'].includes(authorAssoc)) return null;
	const authorLogin = pr.user?.login ?? '?';
	return `Size cap exempted via 'size-cap-exempt' label (author: ${authorLogin}, association: ${authorAssoc}). Reviewable: ${reviewable} lines. Reviewer is responsible for the manual scope review.`;
}

/**
 * Surface the format-only LOC subtraction as a warn for reviewer transparency.
 * No-op when no format-only commits matched.
 */
function reportFormatOnlySubtraction(formatOnly) {
	if (formatOnly.total <= 0) return;
	const list = formatOnly.matched.map((m) => `\`${m.sha}\` (${m.loc} LOC)`).join(', ');
	warn(
		`Excluding ${formatOnly.total} format-only LOC from size cap (commits matching \`^style(<scope>): prettier|format ...\`): ${list}. Reviewer can verify by re-running \`npm run format\` on the PR head — diff should be empty.`
	);
}

function reportPrSize(lineCount, generated, formatOnly) {
	const reviewable = Math.max(0, lineCount - formatOnly.total);
	reportFormatOnlySubtraction(formatOnly);

	const pureDelMsg = checkPureDeletionExemption();
	if (pureDelMsg) {
		message(pureDelMsg);
		return;
	}

	const labelMsg = checkLabelExemption(reviewable);
	if (labelMsg) {
		message(labelMsg);
		return;
	}

	if (reviewable > PR_SIZE_HARD) {
		fail(
			`PR is ${reviewable} reviewable lines (> ${PR_SIZE_HARD}). Split into smaller PRs — reviewers cannot meaningfully review at this scale. Generated files excluded: ${generated} lines. Format-only excluded: ${formatOnly.total} lines.\n\nLegitimate exemption paths: (a) pure-deletion PRs auto-exempt (no additions); (b) repo-trusted author (MEMBER/OWNER/COLLABORATOR) can apply the 'size-cap-exempt' label and re-run CI.`
		);
		return;
	}
	if (reviewable > PR_SIZE_SOFT) {
		warn(
			`PR is ${reviewable} reviewable lines (> ${PR_SIZE_SOFT}). Consider splitting for easier review.`
		);
	}
}

schedule(async () => {
	try {
		const { lineCount, generated } = await computeHumanAuthoredLOC();
		const formatOnly = computeFormatOnlyLOC();
		reportPrSize(lineCount, generated, formatOnly);
	} catch (err) {
		// Git metadata occasionally missing in CI (e.g. shallow clone edge cases).
		// Fail loud with the error so the operator can retry or widen fetch-depth
		// rather than silently skipping the size cap.
		const msg = err instanceof Error ? err.message : String(err);
		fail(
			`Danger size-cap gate could not compute lines-of-code: ${msg}. Retry the CI run or ensure the checkout action uses fetch-depth: 0.`
		);
	}
});

// ── 2. Cross-subsystem sprawl ──────────────────────────────────────────
function topLevelSrcDir(path) {
	const m = path.match(/^src\/([^/]+)\//);
	return m ? m[1] : null;
}
const srcDirs = new Set(changed.map(topLevelSrcDir).filter(Boolean));
if (srcDirs.size > 3) {
	warn(
		`PR touches ${srcDirs.size} top-level src/ subsystems (${[...srcDirs].join(
			', '
		)}). Likely should be split into per-subsystem PRs.`
	);
}

// ── 3. Tests-required for server-code changes (with type-only carve-out) ─
//
// Default: any non-test .ts/.js change under src/lib/server/ requires a
// matching test delta. Carve-out: micro-PRs whose server-code changes are
// 100% import/export type relocations (and similar pure-leaf edits) skip
// the requirement. Same trick as PRs #46/#47/#48 — those are pure type
// surgery with zero behavioral risk; tests would not add coverage.
//
// Carve-out gates (ALL must hold):
//   (a) Total human-authored LOC ≤ MICRO_LOC_CAP
//   (b) No new .ts / .js source files created (test files OK)
//   (c) Every +/- diff line in src/lib/server/** matches one of:
//       - blank line                          /^[+-]\s*$/
//       - import/export type ...              /^[+-]\s*(import|export)\s+type\b/
//       - line comment                        /^[+-]\s*\/\//
//       - block comment line                  /^[+-]\s*\*/
//
// Conservative bias: false-negative (gate fires when it shouldn't, e.g. on
// multi-line import { type X, type Y } blocks) is preferred over
// false-positive (gate skips real behavioral change). When carve-out fires,
// we emit a warn() recording the heuristic + LOC count for audit.
//
// Audit: PR comment shows EITHER fail() (no carve-out) OR warn() with the
// LOC count + file count. No silent passes. Mechanical detection only —
// no labels, no titles, no human override.
//
// References:
//   - https://danger.systems/js/reference.html (linesOfCode, diffForFile,
//     created_files, schedule)
//   - https://danger.systems/js/guides/the_dangerfile.html (async via
//     schedule is required)
//   - https://github.com/danger/danger-js/blob/main/source/dsl/GitDSL.ts
//     (TextDiff shape: {before, after, diff, added, removed})

const MICRO_LOC_CAP = 10;
const TYPE_ONLY_LINE_PATTERNS = [
	/^[+-]\s*$/,
	/^[+-]\s*(import|export)\s+type\b/,
	/^[+-]\s*\/\//,
	/^[+-]\s*\*/
];

// Tier-2 (fallow-cleanup) line patterns. Matches:
//   - Any deletion line (`-...`) — deletions are non-behavioral if tsc + eslint
//     + sentrux all pass (which they must to reach this gate). The cleanup PR
//     workflow specifically uses tsc/eslint/sentrux as the behavioral
//     correctness check; tests are not the right tool for "did I correctly
//     identify dead code".
//   - Blank line
//   - Comment additions: `+ //…`, `+ /*…`, `+ *…`, `+ */…`. Covers
//     `// fallow-ignore-next-line complexity` suppressions and `@internal`
//     JSDoc additions.
//   - `+ export ` / `+ async function ` / `+ function ` lines. Covers the
//     `export NAME` → `function NAME` downgrade pattern used in Phase 2b/2c
//     where idiomatic helpers had their export keyword stripped.
//
// Behavioral additions (new logic, new branches, new state mutations) MUST
// fall outside these patterns and trigger the fail() — fail-closed bias.
const CLEANUP_LINE_PATTERNS = [
	/^-/,
	/^[+-]\s*$/,
	/^\+\s*\/\//,
	/^\+\s*\*/,
	/^\+\s*\/\*/,
	/^\+\s*export\s/,
	/^\+\s*(async\s+)?function\s/
];

/**
 * True for non-test source files under src/lib/server/.
 * Test files under src/lib/server/** are matched by the testChanged predicate
 * below, not by this one.
 */
function isServerSourceFile(path) {
	if (!path.startsWith('src/lib/server/')) return false;
	if (!/\.(ts|js)$/.test(path)) return false;
	return !/\.(test|spec)\.(ts|js)$/.test(path);
}
const serverCodeChanged = changed.some(isServerSourceFile);
// Only match server-related test locations. Prior regex accepted any src/
// test (e.g. src/lib/components/**/*.test.ts), letting a UI-only test satisfy
// a server-code-changed gate. Narrow to server inline tests (src/lib/server)
// + anything under tests/ (integration/unit/security/etc., which do exercise
// server behavior by convention in this repo).
const testChanged = changed.some((f) =>
	/^(src\/lib\/server|tests)\/.*\.(test|spec)\.(ts|js)$/.test(f)
);

/**
 * True if no new .ts/.js source files were created (test/spec/.d files
 * are allowed). Part of the micro-PR type-only carve-out: even a 10-line
 * PR that introduces a brand-new server module needs its own test, no
 * matter what the diff content looks like.
 */
function noNewSourceFilesCreated() {
	return (danger.git.created_files || []).every(
		(f) => !/\.(ts|js)$/.test(f) || /\.(test|spec|d)\./.test(f)
	);
}

/**
 * True if every meaningful added/removed line in a TextDiff matches one of
 * TYPE_ONLY_LINE_PATTERNS (blank, type import/export, comment).
 */
function isDiffTypeOnly(textDiff) {
	const meaningful = textDiff.diff
		.split('\n')
		.filter((l) => /^[+-]/.test(l) && !/^[+-]{3}/.test(l));
	return meaningful.every((l) => TYPE_ONLY_LINE_PATTERNS.some((re) => re.test(l)));
}

/** Single-file wrapper around isDiffTypeOnly that fetches the TextDiff. */
async function fileDiffIsTypeOnly(file) {
	const td = await danger.git.diffForFile(file);
	return Boolean(td) && isDiffTypeOnly(td);
}

/**
 * True if every changed file under src/lib/server/ has a type-only diff.
 * Returns false on the first non-type-only file or unavailable diff.
 */
async function allServerFilesTypeOnly(serverFiles) {
	if (serverFiles.length === 0) return false;
	for (const f of serverFiles) {
		if (!(await fileDiffIsTypeOnly(f))) return false;
	}
	return true;
}

/**
 * Tier-2 cleanup-only diff check. Mirrors isDiffTypeOnly but uses
 * CLEANUP_LINE_PATTERNS (deletions + comment/suppression additions +
 * export-keyword downgrades).
 */
function isDiffCleanupOnly(textDiff) {
	const meaningful = textDiff.diff
		.split('\n')
		.filter((l) => /^[+-]/.test(l) && !/^[+-]{3}/.test(l));
	return meaningful.every((l) => CLEANUP_LINE_PATTERNS.some((re) => re.test(l)));
}

async function fileDiffIsCleanupOnly(file) {
	const td = await danger.git.diffForFile(file);
	return Boolean(td) && isDiffCleanupOnly(td);
}

async function allServerFilesCleanupOnly(serverFiles) {
	if (serverFiles.length === 0) return false;
	for (const f of serverFiles) {
		if (!(await fileDiffIsCleanupOnly(f))) return false;
	}
	return true;
}

/**
 * Tier-1: micro type-only carve-out (≤ MICRO_LOC_CAP, type-import/export only).
 * Conservative — any error or non-match returns false; caller falls through.
 */
async function tryTier1TypeOnlyCarveOut(lineCount, serverFiles) {
	if (lineCount > MICRO_LOC_CAP) return false;
	if (!noNewSourceFilesCreated()) return false;
	if (!(await allServerFilesTypeOnly(serverFiles))) return false;
	warn(
		`Tests-required gate skipped (Tier-1, type-only): PR is ${lineCount} human-authored line(s) and contains only type-import/export edits across ${serverFiles.length} server file(s). Auditable via diff. (Carve-out rule: dangerfile.js, see TYPE_ONLY_LINE_PATTERNS.)`
	);
	return true;
}

/**
 * Tier-2: fallow-cleanup carve-out (any LOC, deletions + suppressions +
 * comments + export-keyword downgrades only). Used by fallow audit batches
 * that touch server code without behavior change. Falls back to fail() on
 * any line that pattern-matching can't classify as non-behavioral.
 */
async function tryTier2CleanupCarveOut(lineCount, serverFiles) {
	if (!noNewSourceFilesCreated()) return false;
	if (!(await allServerFilesCleanupOnly(serverFiles))) return false;
	warn(
		`Tests-required gate skipped (Tier-2, fallow-cleanup): PR is ${lineCount} human-authored line(s) across ${serverFiles.length} server file(s); every meaningful diff line is a deletion, comment, suppression, or export-keyword downgrade. Auditable via diff. (Carve-out rule: dangerfile.js, see CLEANUP_LINE_PATTERNS.)`
	);
	return true;
}

/**
 * Evaluates whether the tests-required gate can be skipped via either tier.
 * Returns true on skip (warn() emitted), false on fall-through to fail().
 */
async function shouldSkipTestsGate() {
	const { lineCount } = await computeHumanAuthoredLOC();
	const serverFiles = changed.filter((f) => f.startsWith('src/lib/server/'));
	if (await tryTier1TypeOnlyCarveOut(lineCount, serverFiles)) return true;
	return tryTier2CleanupCarveOut(lineCount, serverFiles);
}

function testsGateInactive() {
	// Gate doesn't fire (no server code) OR is already satisfied (test delta present).
	return !serverCodeChanged || testChanged;
}

async function tryCarveOutOrFallthrough() {
	try {
		return await shouldSkipTestsGate();
	} catch (err) {
		// Couldn't evaluate carve-out (e.g. shallow clone, missing git
		// metadata). Fall through to fail() — fail-closed bias.
		const msg = err instanceof Error ? err.message : String(err);
		warn(
			`Tests-required carve-out skipped due to git error: ${msg}. Falling back to strict gate.`
		);
		return false;
	}
}

schedule(async () => {
	if (testsGateInactive()) return;
	if (await tryCarveOutOrFallthrough()) return;
	fail(
		'Server code under src/lib/server/ changed but no test files were added or modified. Add unit or integration tests.'
	);
});

// ── 4. Migration vs schema drift ───────────────────────────────────────
const migrationTouched = changed.some((f) => f.startsWith('src/lib/server/db/migrations/'));
const schemaTouched = changed.some((f) => f === 'src/lib/server/db/schema.sql');
if (migrationTouched && !schemaTouched) {
	warn(
		'Migration files changed but src/lib/server/db/schema.sql was not updated. Keep the canonical schema in sync.'
	);
}
if (schemaTouched && !migrationTouched) {
	warn(
		'schema.sql changed but no new migration file was added. Fresh clones will be fine; existing databases need a migration.'
	);
}

// ── 5. Lockfile sync (dependency sections ↔ package-lock.json) ────────────
/**
 * Pattern from https://danger.systems/js/tutorials/dependencies.
 *
 * The "starting simple" example in the tutorial fires on ANY change to
 * package.json — including script edits, metadata bumps, and engines
 * adjustments — none of which require a lockfile update. The same tutorial
 * page recommends evolving the rule via `JSONDiffForFile` so it only
 * triggers on actual dependency-section diffs:
 *   "Convert the check for the package and lockfile to use
 *    `JSONDiffForFile` so that it only warns on `dependencies` or
 *    `devDependencies`."
 *   — https://danger.systems/js/tutorials/dependencies#building-from-here
 *
 * Implementation: inspect the JSON diff of package.json. Fail only when
 * `dependencies` / `devDependencies` / `peerDependencies` /
 * `optionalDependencies` actually changed and the lockfile didn't follow.
 * Script / metadata / engines changes pass silently. Wrapped in
 * `schedule()` so the async call is awaited before Danger reports.
 */
const DEPENDENCY_KEYS = [
	'dependencies',
	'devDependencies',
	'peerDependencies',
	'optionalDependencies'
];

schedule(async () => {
	const pkgChanged = changed.includes('package.json');
	const lockChanged = changed.includes('package-lock.json');
	if (!pkgChanged && lockChanged) {
		warn(
			'package-lock.json changed without a corresponding package.json change. Usually intentional (`npm audit fix`, dedupe) but worth a reviewer sanity check.'
		);
		return;
	}
	if (!pkgChanged) return;

	const diff = await danger.git.JSONDiffForFile('package.json');
	const depsChanged = DEPENDENCY_KEYS.some((k) => diff[k] !== undefined);
	if (depsChanged && !lockChanged) {
		fail(
			'package.json dependency sections changed but package-lock.json was not updated. Run `npm install` locally and commit the updated lockfile — otherwise `npm ci` on CI will install different transitive versions than were tested.'
		);
	}
});

// ── 6. Native-addon dependency guard ──────────────────────────────────────
/**
 * Argos-specific (per AGENTS.md): @sveltejs/adapter-node only externalizes
 * `dependencies`. Native addons (better-sqlite3, node-pty) MUST be in
 * `dependencies`, NOT `devDependencies`, or the production bundle breaks
 * with `ReferenceError: __filename is not defined` at server startup.
 *
 * Uses JSONDiffForFile per the official tutorial pattern.
 */
const NATIVE_ADDONS = ['better-sqlite3', 'node-pty'];

async function getNativeAddonLeakages() {
	try {
		const diff = await danger.git.JSONDiffForFile('package.json');
		const addedDev = diff?.devDependencies?.added ?? [];
		return NATIVE_ADDONS.filter((mod) => addedDev.includes(mod));
	} catch {
		return null;
	}
}

schedule(async () => {
	if (!changed.includes('package.json')) return;
	const leaked = await getNativeAddonLeakages();
	if (leaked === null) {
		warn(
			'Native-addon dependency guard skipped: could not read JSONDiffForFile(package.json). Reviewer: verify manually.'
		);
		return;
	}
	if (leaked.length === 0) return;
	fail(
		`Native addons must stay in \`dependencies\` (NOT \`devDependencies\`) per AGENTS.md. Detected in devDependencies: ${leaked.join(', ')}. @sveltejs/adapter-node only externalizes \`dependencies\`; native addons in devDeps get bundled into the ESM server chunk and break at server startup with \`ReferenceError: __filename is not defined\`.`
	);
});

// ── 7. New-dependency visibility comment ─────────────────────────────────
/**
 * When ANY dependency is added or removed in this PR, post a `message()`
 * listing the entries for reviewer audit. Aligns with the Argos rule
 * "no npm install without approval" — if a new dep slipped in, this rule
 * makes it visible in the PR comment. Informational only (no fail/warn).
 *
 * Pattern from https://danger.systems/js/tutorials/dependencies.
 */
function summarizeDepDiff(diff) {
	const buckets = [
		['New dependencies', diff?.dependencies?.added ?? []],
		['New devDependencies', diff?.devDependencies?.added ?? []],
		['Removed dependencies', diff?.dependencies?.removed ?? []],
		['Removed devDependencies', diff?.devDependencies?.removed ?? []]
	];
	return buckets
		.filter(([, items]) => items.length > 0)
		.map(([label, items]) => `**${label}**: ${items.map((d) => `\`${d}\``).join(', ')}`);
}

schedule(async () => {
	if (!changed.includes('package.json')) return;
	let diff;
	try {
		diff = await danger.git.JSONDiffForFile('package.json');
	} catch {
		return;
	}
	const lines = summarizeDepDiff(diff);
	if (lines.length === 0) return;
	message(
		`Dependency changes in this PR:\n\n${lines.join('\n')}\n\nReviewer: verify per Argos's "no npm install without approval" rule. If the author didn't explicitly request the install, the dep should not be in this PR.`
	);
});

// ── 8. PR description body quality ───────────────────────────────────────
/**
 * Encourages a non-empty PR description with enough context to review
 * effectively. The PR body is what reviewers see first on GitHub;
 * commit messages don't surface in the summary view.
 */
function checkPrBodyQuality() {
	const body = danger.github?.pr?.body?.trim() ?? '';
	if (body.length === 0) {
		warn(
			'PR description is empty. Add a Summary + Test plan so reviewers know what changed and how it was verified.'
		);
		return;
	}
	if (body.length < 100) {
		warn(
			`PR description is short (${body.length} chars). Consider adding: (1) a one-paragraph Summary, (2) a Test plan checklist, (3) any cited docs / issues. See prior PR templates for examples.`
		);
	}
}
checkPrBodyQuality();
