/* eslint-disable no-undef */
/**
 * Argos PR shape rules via danger.js.
 *
 * Runs per-PR in .github/workflows/danger.yml. Supplements commitlint
 * (which enforces message shape) and CodeRabbit (which reviews code
 * quality) with PR-level structural rules:
 *
 *   1. Size cap — warn on PRs the reviewer can't reasonably load.
 *   2. Cross-subsystem sprawl — warn when a single PR spans more than
 *      three top-level src/ areas.
 *   3. Tests-required — fail when server code changes without a
 *      matching test delta.
 *   4. Migration-drift — warn when migrations and schema.sql drift
 *      out of sync.
 *
 * These rules start conservative (mostly warn) and can be tightened
 * once the team sees how they land on live PRs. `fail` rules block the
 * merge; `warn` rules post a comment but do not block.
 */

// Include deleted files too — a PR that deletes server code is still a
// server-code change and must satisfy the tests-required gate. Dedupe so a
// file that appears in multiple danger.git arrays isn't counted twice.
const changed = Array.from(
	new Set([
		...(danger.git.modified_files || []),
		...(danger.git.created_files || []),
		...(danger.git.deleted_files || [])
	])
);

// ── 1. PR size cap (human-authored lines only — exclude generated files) ─
// Hard cap raised from 1200 → 2000 on 2026-04-29 to support phase-level
// PR bundling per memory `feedback_bulk_pr_bundling.md`. Spec-026 sub-phases
// total ~1700-2000 LOC when bundled (wrapper + spec docs + consumer
// migrations + roadmap flip). 2000 is the new ceiling; soft warn at 500
// stays as the splitting nudge for non-phase-bundled PRs.
const PR_SIZE_SOFT = 500;
const PR_SIZE_HARD = 2000;
// Globs for files that bloat the raw diff without being reviewable prose.
// Lock files, changelogs, and snapshot fixtures all fall in here — they can
// legitimately add thousands of lines on a small PR and would defeat the gate.
const GENERATED_GLOBS = [
	'package-lock.json',
	'**/package-lock.json',
	'yarn.lock',
	'pnpm-lock.yaml',
	'**/pnpm-lock.yaml',
	'CHANGELOG.md',
	'**/CHANGELOG.md',
	// Fallow baseline files are machine-generated by `fallow {dead-code,health,dupes}
	// --save-baseline`. They snapshot the day-1 finding state and refresh on
	// re-baseline; reviewers shouldn't count their JSON line counts against
	// the human-authored LOC cap.
	//
	// PR #108 (session-3 fallow batch) hit the 2000-LOC cap reporting 8899
	// human-authored lines — the baseline regenerations contributed ~6500 of
	// those because some glob libraries default to dotfiles=false. Enumerate
	// the three baseline filenames explicitly so the exclusion fires
	// regardless of glob-library dotfile policy. The wildcards stay as a
	// catch-all for any future fallow-* baseline file.
	'.fallow-deadcode-baseline.json',
	'.fallow-dupes-baseline.json',
	'.fallow-health-baseline.json',
	'.fallow-*-baseline.json',
	'**/.fallow-*-baseline.json',
	// Vendored upstream code under static/webtak/{novnc,vendor}/ is
	// byte-for-byte from novnc/noVNC + nodeca/pako. Reviewers don't audit it
	// line-by-line — it's a snapshot of an external project. Treat as
	// generated for size-cap purposes; the manifest test
	// (tests/integration/vnc-vendor-manifest.test.ts) is what reviewers
	// actually look at.
	'static/webtak/novnc/**',
	'static/webtak/vendor/**',
	// TEMPORARY — V3 (NVIDIA UI) mechanical-copy carve-out (added 2026-05-18,
	// spec-027 phase C1). C1 copies V1's component tree into
	// src/lib/components/v3/** and the v3 route at src/routes/dashboard/v3/**
	// verbatim — only import prefixes change — and verifies each copied file
	// by diffing it against its V1 original. There is nothing to review
	// line-by-line, same rationale as the static/webtak/vendor exclusion above.
	// REMOVE this block when C1 completes: C2's hand-written NVIDIA polish
	// edits these same files and MUST count toward the size cap.
	'src/lib/components/v3/**',
	'src/routes/dashboard/v3/**'
];
/**
 * Human-authored LOC = total LOC minus everything matched by GENERATED_GLOBS.
 * Used by both the size-cap gate and the micro-PR carve-out.
 */
async function computeHumanAuthoredLOC() {
	const total = await danger.git.linesOfCode();
	let generated = 0;
	for (const pat of GENERATED_GLOBS) {
		generated += await danger.git.linesOfCode(pat);
	}
	return { lineCount: Math.max(0, total - generated), generated };
}

// Format-only commits are deterministic prettier / formatter output. No
// review value is added by capping their LOC — re-running the same tool on
// the pre-commit state reproduces the diff exactly. Detected by Conventional
// Commits subject pattern: `style(<scope>): prettier ...` or
// `style(<scope>): format ...`. Authors opt in by using these subjects for
// pure formatter sweeps. Mixed PRs (format commit + non-format commit) get
// per-commit subtraction: the format commit's LOC contribution is excluded
// while non-format commits' LOC still counts toward the cap.
//
// Discovered 2026-05-06: PR #115 was a 6031-LOC bundle of which ~5800 was a
// single `npm run format` sweep on Phase 9 spec docs + .svelte files.
// Splitting an auto-format diff into per-file PRs adds zero review signal
// at >100× CI cost. Codifying the carve-out in `dangerfile.js` is the
// professional alternative to admin-bypassing the gate (see
// `feedback_no_admin_bypass_daily_loc_cap.md`).
const FORMAT_COMMIT_RE = /^style\([^)]+\):\s+(prettier|format)\b/;
const { execSync } = require('node:child_process');

function computeFormatOnlyLOC() {
	const commits = (danger.git && danger.git.commits) || [];
	let total = 0;
	const matched = [];
	for (const c of commits) {
		const subject = ((c && c.message) || '').split('\n')[0];
		if (!FORMAT_COMMIT_RE.test(subject)) continue;
		try {
			const out = execSync(`git show --shortstat --format="" ${c.sha}`, {
				encoding: 'utf8'
			});
			const ins = Number((out.match(/(\d+) insertion/) || ['', 0])[1]);
			const del = Number((out.match(/(\d+) deletion/) || ['', 0])[1]);
			total += ins + del;
			matched.push({ sha: c.sha.slice(0, 7), subject, loc: ins + del });
		} catch {
			// Conservative: a commit whose stat we can't read counts toward cap.
		}
	}
	return { total, matched };
}

function reportPrSize(lineCount, generated, formatOnly) {
	const reviewable = Math.max(0, lineCount - formatOnly.total);
	if (formatOnly.total > 0) {
		const list = formatOnly.matched.map((m) => `\`${m.sha}\` (${m.loc} LOC)`).join(', ');
		warn(
			`Excluding ${formatOnly.total} format-only LOC from size cap (commits matching \`^style(<scope>): prettier|format ...\`): ${list}. Reviewer can verify by re-running \`npm run format\` on the PR head — diff should be empty.`
		);
	}
	if (reviewable > PR_SIZE_HARD) {
		fail(
			`PR is ${reviewable} reviewable lines (> ${PR_SIZE_HARD}). Split into smaller PRs — reviewers cannot meaningfully review at this scale. Generated files excluded: ${generated} lines. Format-only excluded: ${formatOnly.total} lines.`
		);
		return;
	}
	if (reviewable > PR_SIZE_SOFT) {
		warn(
			`PR is ${reviewable} reviewable lines (> ${PR_SIZE_SOFT}). Consider splitting for easier review.`
		);
	}
}

schedule(async () => {
	try {
		const { lineCount, generated } = await computeHumanAuthoredLOC();
		const formatOnly = computeFormatOnlyLOC();
		reportPrSize(lineCount, generated, formatOnly);
	} catch (err) {
		// Git metadata occasionally missing in CI (e.g. shallow clone edge cases).
		// Fail loud with the error so the operator can retry or widen fetch-depth
		// rather than silently skipping the size cap.
		const msg = err instanceof Error ? err.message : String(err);
		fail(
			`Danger size-cap gate could not compute lines-of-code: ${msg}. Retry the CI run or ensure the checkout action uses fetch-depth: 0.`
		);
	}
});

// ── 2. Cross-subsystem sprawl ──────────────────────────────────────────
function topLevelSrcDir(path) {
	const m = path.match(/^src\/([^/]+)\//);
	return m ? m[1] : null;
}
const srcDirs = new Set(changed.map(topLevelSrcDir).filter(Boolean));
if (srcDirs.size > 3) {
	warn(
		`PR touches ${srcDirs.size} top-level src/ subsystems (${[...srcDirs].join(
			', '
		)}). Likely should be split into per-subsystem PRs.`
	);
}

// ── 3. Tests-required for server-code changes (with type-only carve-out) ─
//
// Default: any non-test .ts/.js change under src/lib/server/ requires a
// matching test delta. Carve-out: micro-PRs whose server-code changes are
// 100% import/export type relocations (and similar pure-leaf edits) skip
// the requirement. Same trick as PRs #46/#47/#48 — those are pure type
// surgery with zero behavioral risk; tests would not add coverage.
//
// Carve-out gates (ALL must hold):
//   (a) Total human-authored LOC ≤ MICRO_LOC_CAP
//   (b) No new .ts / .js source files created (test files OK)
//   (c) Every +/- diff line in src/lib/server/** matches one of:
//       - blank line                          /^[+-]\s*$/
//       - import/export type ...              /^[+-]\s*(import|export)\s+type\b/
//       - line comment                        /^[+-]\s*\/\//
//       - block comment line                  /^[+-]\s*\*/
//
// Conservative bias: false-negative (gate fires when it shouldn't, e.g. on
// multi-line import { type X, type Y } blocks) is preferred over
// false-positive (gate skips real behavioral change). When carve-out fires,
// we emit a warn() recording the heuristic + LOC count for audit.
//
// Audit: PR comment shows EITHER fail() (no carve-out) OR warn() with the
// LOC count + file count. No silent passes. Mechanical detection only —
// no labels, no titles, no human override.
//
// References:
//   - https://danger.systems/js/reference.html (linesOfCode, diffForFile,
//     created_files, schedule)
//   - https://danger.systems/js/guides/the_dangerfile.html (async via
//     schedule is required)
//   - https://github.com/danger/danger-js/blob/main/source/dsl/GitDSL.ts
//     (TextDiff shape: {before, after, diff, added, removed})

const MICRO_LOC_CAP = 10;
const TYPE_ONLY_LINE_PATTERNS = [
	/^[+-]\s*$/,
	/^[+-]\s*(import|export)\s+type\b/,
	/^[+-]\s*\/\//,
	/^[+-]\s*\*/
];

// Tier-2 (fallow-cleanup) line patterns. Matches:
//   - Any deletion line (`-...`) — deletions are non-behavioral if tsc + eslint
//     + sentrux all pass (which they must to reach this gate). The cleanup PR
//     workflow specifically uses tsc/eslint/sentrux as the behavioral
//     correctness check; tests are not the right tool for "did I correctly
//     identify dead code".
//   - Blank line
//   - Comment additions: `+ //…`, `+ /*…`, `+ *…`, `+ */…`. Covers
//     `// fallow-ignore-next-line complexity` suppressions and `@internal`
//     JSDoc additions.
//   - `+ export ` / `+ async function ` / `+ function ` lines. Covers the
//     `export NAME` → `function NAME` downgrade pattern used in Phase 2b/2c
//     where idiomatic helpers had their export keyword stripped.
//
// Behavioral additions (new logic, new branches, new state mutations) MUST
// fall outside these patterns and trigger the fail() — fail-closed bias.
const CLEANUP_LINE_PATTERNS = [
	/^-/,
	/^[+-]\s*$/,
	/^\+\s*\/\//,
	/^\+\s*\*/,
	/^\+\s*\/\*/,
	/^\+\s*export\s/,
	/^\+\s*(async\s+)?function\s/
];

/**
 * True for non-test source files under src/lib/server/.
 * Test files under src/lib/server/** are matched by the testChanged predicate
 * below, not by this one.
 */
function isServerSourceFile(path) {
	if (!path.startsWith('src/lib/server/')) return false;
	if (!/\.(ts|js)$/.test(path)) return false;
	return !/\.(test|spec)\.(ts|js)$/.test(path);
}
const serverCodeChanged = changed.some(isServerSourceFile);
// Only match server-related test locations. Prior regex accepted any src/
// test (e.g. src/lib/components/**/*.test.ts), letting a UI-only test satisfy
// a server-code-changed gate. Narrow to server inline tests (src/lib/server)
// + anything under tests/ (integration/unit/security/etc., which do exercise
// server behavior by convention in this repo).
const testChanged = changed.some((f) =>
	/^(src\/lib\/server|tests)\/.*\.(test|spec)\.(ts|js)$/.test(f)
);

/**
 * True if no new .ts/.js source files were created (test/spec/.d files
 * are allowed). Part of the micro-PR type-only carve-out: even a 10-line
 * PR that introduces a brand-new server module needs its own test, no
 * matter what the diff content looks like.
 */
function noNewSourceFilesCreated() {
	return (danger.git.created_files || []).every(
		(f) => !/\.(ts|js)$/.test(f) || /\.(test|spec|d)\./.test(f)
	);
}

/**
 * True if every meaningful added/removed line in a TextDiff matches one of
 * TYPE_ONLY_LINE_PATTERNS (blank, type import/export, comment).
 */
function isDiffTypeOnly(textDiff) {
	const meaningful = textDiff.diff
		.split('\n')
		.filter((l) => /^[+-]/.test(l) && !/^[+-]{3}/.test(l));
	return meaningful.every((l) => TYPE_ONLY_LINE_PATTERNS.some((re) => re.test(l)));
}

/** Single-file wrapper around isDiffTypeOnly that fetches the TextDiff. */
async function fileDiffIsTypeOnly(file) {
	const td = await danger.git.diffForFile(file);
	return Boolean(td) && isDiffTypeOnly(td);
}

/**
 * True if every changed file under src/lib/server/ has a type-only diff.
 * Returns false on the first non-type-only file or unavailable diff.
 */
async function allServerFilesTypeOnly(serverFiles) {
	if (serverFiles.length === 0) return false;
	for (const f of serverFiles) {
		if (!(await fileDiffIsTypeOnly(f))) return false;
	}
	return true;
}

/**
 * Tier-2 cleanup-only diff check. Mirrors isDiffTypeOnly but uses
 * CLEANUP_LINE_PATTERNS (deletions + comment/suppression additions +
 * export-keyword downgrades).
 */
function isDiffCleanupOnly(textDiff) {
	const meaningful = textDiff.diff
		.split('\n')
		.filter((l) => /^[+-]/.test(l) && !/^[+-]{3}/.test(l));
	return meaningful.every((l) => CLEANUP_LINE_PATTERNS.some((re) => re.test(l)));
}

async function fileDiffIsCleanupOnly(file) {
	const td = await danger.git.diffForFile(file);
	return Boolean(td) && isDiffCleanupOnly(td);
}

async function allServerFilesCleanupOnly(serverFiles) {
	if (serverFiles.length === 0) return false;
	for (const f of serverFiles) {
		if (!(await fileDiffIsCleanupOnly(f))) return false;
	}
	return true;
}

/**
 * Tier-1: micro type-only carve-out (≤ MICRO_LOC_CAP, type-import/export only).
 * Conservative — any error or non-match returns false; caller falls through.
 */
async function tryTier1TypeOnlyCarveOut(lineCount, serverFiles) {
	if (lineCount > MICRO_LOC_CAP) return false;
	if (!noNewSourceFilesCreated()) return false;
	if (!(await allServerFilesTypeOnly(serverFiles))) return false;
	warn(
		`Tests-required gate skipped (Tier-1, type-only): PR is ${lineCount} human-authored line(s) and contains only type-import/export edits across ${serverFiles.length} server file(s). Auditable via diff. (Carve-out rule: dangerfile.js, see TYPE_ONLY_LINE_PATTERNS.)`
	);
	return true;
}

/**
 * Tier-2: fallow-cleanup carve-out (any LOC, deletions + suppressions +
 * comments + export-keyword downgrades only). Used by fallow audit batches
 * that touch server code without behavior change. Falls back to fail() on
 * any line that pattern-matching can't classify as non-behavioral.
 */
async function tryTier2CleanupCarveOut(lineCount, serverFiles) {
	if (!noNewSourceFilesCreated()) return false;
	if (!(await allServerFilesCleanupOnly(serverFiles))) return false;
	warn(
		`Tests-required gate skipped (Tier-2, fallow-cleanup): PR is ${lineCount} human-authored line(s) across ${serverFiles.length} server file(s); every meaningful diff line is a deletion, comment, suppression, or export-keyword downgrade. Auditable via diff. (Carve-out rule: dangerfile.js, see CLEANUP_LINE_PATTERNS.)`
	);
	return true;
}

/**
 * Evaluates whether the tests-required gate can be skipped via either tier.
 * Returns true on skip (warn() emitted), false on fall-through to fail().
 */
async function shouldSkipTestsGate() {
	const { lineCount } = await computeHumanAuthoredLOC();
	const serverFiles = changed.filter((f) => f.startsWith('src/lib/server/'));
	if (await tryTier1TypeOnlyCarveOut(lineCount, serverFiles)) return true;
	return tryTier2CleanupCarveOut(lineCount, serverFiles);
}

function testsGateInactive() {
	// Gate doesn't fire (no server code) OR is already satisfied (test delta present).
	return !serverCodeChanged || testChanged;
}

async function tryCarveOutOrFallthrough() {
	try {
		return await shouldSkipTestsGate();
	} catch (err) {
		// Couldn't evaluate carve-out (e.g. shallow clone, missing git
		// metadata). Fall through to fail() — fail-closed bias.
		const msg = err instanceof Error ? err.message : String(err);
		warn(
			`Tests-required carve-out skipped due to git error: ${msg}. Falling back to strict gate.`
		);
		return false;
	}
}

schedule(async () => {
	if (testsGateInactive()) return;
	if (await tryCarveOutOrFallthrough()) return;
	fail(
		'Server code under src/lib/server/ changed but no test files were added or modified. Add unit or integration tests.'
	);
});

// ── 4. Migration vs schema drift ───────────────────────────────────────
const migrationTouched = changed.some((f) => f.startsWith('src/lib/server/db/migrations/'));
const schemaTouched = changed.some((f) => f === 'src/lib/server/db/schema.sql');
if (migrationTouched && !schemaTouched) {
	warn(
		'Migration files changed but src/lib/server/db/schema.sql was not updated. Keep the canonical schema in sync.'
	);
}
if (schemaTouched && !migrationTouched) {
	warn(
		'schema.sql changed but no new migration file was added. Fresh clones will be fine; existing databases need a migration.'
	);
}
