import type { IncomingMessage, ServerResponse } from 'node:http';
import { createServer } from 'node:http';

// build/handler.js is generated by `npm run build` (SvelteKit adapter-node
// output); it does not exist in the source tree at static-analysis time.
// argos-final.service ExecStart's `npm run build && tsx scripts/ops/prod-server.ts`
// guarantees it exists at runtime.
// fallow-ignore-next-line unresolved-import
import { handler } from '../../build/handler.js';
import { handleTerminalUpgrade } from '../../src/lib/server/terminal/handler.js';
import { preSpawnDefaultSession } from '../../src/lib/server/terminal/session.js';

const PORT = Number(process.env.PORT ?? 5173);
const HOST = process.env.HOST ?? '0.0.0.0';

const httpServer = createServer((req: IncomingMessage, res: ServerResponse) => {
	handler(req, res, () => {
		if (!res.headersSent) {
			res.statusCode = 404;
			res.end('Not Found');
		}
	});
});

httpServer.on('upgrade', (req, socket, head) => {
	if (handleTerminalUpgrade(req, socket, head)) return;
	socket.destroy();
});

httpServer.listen(PORT, HOST, () => {
	console.warn(`[argos-prod] listening on http://${HOST}:${PORT}`);
});

if (process.env.ARGOS_TERMINAL_PRESPAWN === '1') {
	void preSpawnDefaultSession();
}

const shutdown = () => {
	httpServer.close(() => process.exit(0));
	setTimeout(() => process.exit(1), 5000).unref();
};
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
