/**
 * Intel sub-tab definitions, descriptions, and extra column configs
 * for the Devices panel's recon-based category views.
 *
 * @module
 */

import type { ReconTarget } from '$lib/stores/dashboard/recon-store';

export interface TabDef {
	id: string;
	label: string;
}

export const INTEL_TABS: TabDef[] = [
	{ id: 'all', label: 'ALL' },
	{ id: 'weak-security', label: 'WEAK SEC' },
	{ id: 'wps', label: 'WPS' },
	{ id: 'hidden', label: 'HIDDEN' },
	{ id: 'busy-aps', label: 'BUSY APs' },
	{ id: 'gps', label: 'GPS' },
	{ id: 'alerts', label: 'ALERTS' },
	{ id: 'whitelist', label: 'WHITELIST' }
];

export const INTEL_DESCRIPTIONS: Record<string, string> = {
	'weak-security':
		'Networks using Open, WEP, or TKIP encryption — vulnerable to interception or cracking. These are high-priority targets for security assessment.',
	wps: 'Access points with Wi-Fi Protected Setup enabled. WPS PINs can be brute-forced, bypassing WPA/WPA2 encryption entirely.',
	hidden: 'Cloaked networks or devices broadcasting without an SSID. Hidden networks are still detectable and often indicate sensitive infrastructure.',
	'busy-aps':
		'Access points with connected clients. High client counts indicate important infrastructure or potential targets for deauthentication.',
	gps: 'Devices with GPS location data captured. Useful for physical tracking, wardriving maps, and correlating device positions.',
	alerts: 'Security alerts generated by Kismet during monitoring — rogue APs, deauthentication attacks, SSID spoofing, and other anomalies.'
};

export type ExtraColumn = {
	id: string;
	label: string;
	render: (t: ReconTarget) => string;
};

export const WPS_EXTRA_COLUMNS: ExtraColumn[] = [
	{
		id: 'wps_version',
		label: 'WPS VER',
		render: (t) => (t.wps_version ? `v${t.wps_version}` : '?')
	}
];

export const BUSY_EXTRA_COLUMNS: ExtraColumn[] = [
	{
		id: 'client_list',
		label: 'CLIENT MACs',
		render: (t) => t.associated_clients?.slice(0, 3).join(', ') || '-'
	}
];

export const GPS_EXTRA_COLUMNS: ExtraColumn[] = [
	{
		id: 'gps_lat',
		label: 'LAT',
		render: (t) => (t.latitude ? t.latitude.toFixed(5) : '-')
	},
	{
		id: 'gps_lon',
		label: 'LON',
		render: (t) => (t.longitude ? t.longitude.toFixed(5) : '-')
	}
];
